// Generated by scripts/generate_contracts.py. Do not edit.
export interface ApiSchemas {
  "ActiveInterval": { "ended_at"?: (string | null); "quality": "observed" | "estimated" | "unknown"; "started_at": string; "state": "running" | "retry_wait" | "recovering" | "pause_requested" | "stop_requested" }
  "Chat": { "archived": boolean; "created_at": string; "id": string; "project_id": string; "title": string; "updated_at": string; "version": number }
  "ChatArchive": { "archive"?: boolean; "expected_version": number }
  "ChatCreate": { "title": string }
  "ChatUpdate": { "expected_version": number; "title": string }
  "CommandAccepted": { "applied_at"?: (string | null); "command_id": string; "response"?: (Record<string, unknown> | null); "sequence": number; "status": "accepted" | "applied" | "rejected" | "superseded" }
  "DraftPublish": { "expected_version": number }
  "HTTPValidationError": { "detail"?: Array<ApiSchemas["ValidationError"]>; [key: string]: unknown }
  "HarnessProfile": { "archived": boolean; "created_at": string; "executable_path": (string | null); "harness_kind": "codex" | "opencode"; "id": string; "name": string; "settings": Record<string, unknown>; "updated_at": string; "version": number }
  "HarnessProfileCreate": { "executable_path"?: (string | null); "harness_kind": "codex" | "opencode"; "name": string; "settings"?: Record<string, unknown> }
  "HarnessProfileUpdate": { "executable_path"?: (string | null); "expected_version": number; "name"?: (string | null); "settings"?: (Record<string, unknown> | null) }
  "Message": { "archived": boolean; "chat_id": string; "content": string; "created_at": string; "id": string; "role": string; "version": number }
  "MessageCreate": { "content": string; "role": "user" | "assistant" | "system" | "note" }
  "MessageUpdate": { "content": string; "expected_version": number }
  "PairRequest": { "code": string; [key: string]: unknown }
  "PipelineBinding": { "archived": boolean; "branch_policy": "run_branch" | "current"; "command_filter": Array<string>; "created_at": string; "dirty_policy": "strict" | "allow_nonoverlap"; "id": string; "limit_overrides": Record<string, unknown>; "model_overrides": Record<string, string>; "name": string; "project_id": string; "role_assignments": Record<string, string>; "updated_at": string; "version": number; "version_id": string }
  "PipelineBindingCreate": { "branch_policy"?: "run_branch" | "current"; "command_filter"?: Array<string>; "dirty_policy"?: "strict" | "allow_nonoverlap"; "limit_overrides"?: Record<string, number>; "model_overrides"?: Record<string, string>; "name": string; "project_id": string; "role_assignments"?: Record<string, string> }
  "PipelineBindingUpdate": { "branch_policy"?: ("run_branch" | "current" | null); "command_filter"?: (Array<string> | null); "dirty_policy"?: ("strict" | "allow_nonoverlap" | null); "expected_version": number; "limit_overrides"?: (Record<string, number> | null); "model_overrides"?: (Record<string, string> | null); "name"?: (string | null); "role_assignments"?: (Record<string, string> | null) }
  "PipelineDraft": { "graph"?: Record<string, unknown>; "inputs"?: Record<string, unknown>; "required_features"?: Array<string>; "settings"?: ApiSchemas["SettingsOverrides"] }
  "PipelineDraftUpdate": { "expected_version": number; "graph"?: Record<string, unknown>; "inputs"?: Record<string, unknown>; "required_features"?: Array<string>; "settings"?: ApiSchemas["SettingsOverrides"] }
  "PipelineTemplate": { "archived": boolean; "created_at": string; "description": string; "draft": ApiSchemas["PipelineDraft"]; "id": string; "kind": "user" | "system"; "name": string; "schema_version": string; "updated_at": string; "version": number }
  "PipelineTemplateCreate": { "description"?: string; "name": string; "schema_version"?: string }
  "PipelineTemplateUpdate": { "description"?: (string | null); "expected_version": number; "name"?: (string | null) }
  "PipelineVersion": { "created_at": string; "execution_hash": string; "graph": Record<string, unknown>; "id": string; "immutable"?: true; "inputs": Record<string, unknown>; "policy_hash": string; "required_features": Array<string>; "schema_version": string; "settings": ApiSchemas["SettingsOverrides"]; "template_id": string; "version_number": number }
  "PipelineVersionCreate": { "graph": Record<string, unknown>; "inputs"?: Record<string, unknown>; "required_features"?: Array<string>; "settings"?: ApiSchemas["SettingsOverrides"] }
  "Project": { "archived": boolean; "created_at": string; "id": string; "name": string; "updated_at": string; "version": number; "workspace": ApiSchemas["WorkspaceInfo"] }
  "ProjectArchive": { "archive"?: boolean; "expected_version": number }
  "ProjectCreate": { "name": string; "workspace_path": string }
  "ProjectUpdate": { "expected_version": number; "name"?: (string | null) }
  "ProviderConnection": { "archived": boolean; "base_url": string; "catalog_fetched_at": (string | null); "catalog_models": Array<string>; "catalog_ttl_seconds": number; "created_at": string; "has_secret": boolean; "id": string; "last_test_at": (string | null); "last_test_status": (string | null); "manual_models": Array<string>; "name": string; "protocol": "http" | "https"; "provider_kind": "openai_compatible" | "loopback"; "updated_at": string; "version": number }
  "ProviderConnectionCreate": { "base_url": string; "catalog_ttl_seconds"?: number; "manual_models"?: Array<string>; "name": string; "provider_kind"?: "openai_compatible" | "loopback"; "secret"?: (string | null) }
  "ProviderConnectionUpdate": { "base_url"?: (string | null); "catalog_ttl_seconds"?: (number | null); "expected_version": number; "manual_models"?: (Array<string> | null); "name"?: (string | null); "secret"?: (string | null) }
  "ProviderTest": { "detail"?: (string | null); "models": Array<string>; "status": "ok" | "failed"; "tested_at": string }
  "ResolvedSettingSource": { "locked": boolean; "name": string; "source": "run" | "binding" | "template" | "node" | "default"; "value": unknown }
  "ResolvedSettings": { "execution_hash": string; "policy_hash": string; "schema_version": string; "settings": Array<ApiSchemas["ResolvedSettingSource"]> }
  "Run": { "active_intervals"?: Array<ApiSchemas["ActiveInterval"]>; "binding_id": string; "chat_id": (string | null); "created_at": string; "execution_hash": string; "finished_at": (string | null); "id": string; "idempotency_key": string; "pipeline_version_id": string; "policy_hash": string; "project_id": string; "schema_version": string; "snapshot_hash": string; "started_at": (string | null); "state": ApiSchemas["RunState"]; "state_version": number; "updated_at": string; "waiting_reason"?: (ApiSchemas["WaitingReason"] | null); "worker_generation": number; "worker_id": (string | null) }
  "RunCommand": { "command_id": string; "command_type": "pause" | "stop" | "cancel" | "resume" | "resolve"; "expected_state_version": number; "payload"?: Record<string, unknown> }
  "RunStart": { "binding_id": string; "chat_id"?: (string | null); "idempotency_key": string; "initiator"?: string; "inputs"?: Record<string, unknown>; "message"?: (string | null); "overrides"?: ApiSchemas["SettingsOverrides"]; "project_id": string }
  "RunState": "queued" | "running" | "pause_requested" | "paused" | "stop_requested" | "stopped" | "retry_wait" | "waiting_input" | "recovering" | "completed" | "failed" | "cancelled"
  "SettingsOverrides": { "branch_policy"?: ("run_branch" | "current" | null); "command_filter"?: (Array<string> | null); "dirty_policy"?: ("strict" | "allow_nonoverlap" | null); "limit_overrides"?: (Record<string, number> | null); "model_overrides"?: (Record<string, string> | null); "role_assignments"?: (Record<string, string> | null) }
  "ValidationError": { "ctx"?: Record<string, unknown>; "input"?: unknown; "loc": Array<(string | number)>; "msg": string; "type": string; [key: string]: unknown }
  "WaitingReason": { "allowed_actions": Array<"resolve" | "resume" | "pause" | "stop" | "cancel">; "blocked_operation_id"?: (string | null); "code": "missing_data" | "permission_required" | "limit_exceeded" | "auth_required" | "secret_unavailable" | "model_unavailable" | "external_change_detected" | "unknown_external_result" | "invalid_response_format" | "workspace_conflict" | "process_not_responding" | "port_unavailable" | "path_violation" | "import_trust_required" | "schema_unsupported" | "configuration_invalid" | "storage_unavailable" | "signing_required" | "no_progress"; "details"?: Record<string, unknown>; "resolution_schema"?: Record<string, unknown> }
  "WorkspaceInfo": { "entered_path": string; "git_default_branch": (string | null); "git_dirty": boolean; "git_head_sha": (string | null); "git_remote_url": (string | null); "git_root_path": (string | null); "identity_dev": number; "identity_ino": number; "normalized_path": string }
}

export interface ApiOperations {
  "POST /api/auth/logout": { body: never; parameters: Record<string, never>; responses: { "200": unknown } }
  "POST /api/auth/pair": { body: ApiSchemas["PairRequest"]; parameters: Record<string, never>; responses: { "200": unknown; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/auth/session": { body: never; parameters: Record<string, never>; responses: { "200": Record<string, unknown> } }
  "GET /api/bindings": { body: never; parameters: { "query.project_id"?: (string | null); "query.include_archived"?: boolean }; responses: { "200": Array<ApiSchemas["PipelineBinding"]>; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/bindings/{binding_id}": { body: never; parameters: { "path.binding_id": string }; responses: { "200": ApiSchemas["PipelineBinding"]; "422": ApiSchemas["HTTPValidationError"] } }
  "PATCH /api/bindings/{binding_id}": { body: ApiSchemas["PipelineBindingUpdate"]; parameters: { "path.binding_id": string }; responses: { "200": ApiSchemas["PipelineBinding"]; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/bindings/{binding_id}/archive": { body: never; parameters: { "path.binding_id": string; "query.expected_version": number }; responses: { "200": ApiSchemas["PipelineBinding"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/bindings/{binding_id}/resolved": { body: never; parameters: { "path.binding_id": string }; responses: { "200": ApiSchemas["ResolvedSettings"]; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/bindings/{binding_id}/resolved": { body: ApiSchemas["SettingsOverrides"]; parameters: { "path.binding_id": string }; responses: { "200": ApiSchemas["ResolvedSettings"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/capabilities": { body: never; parameters: Record<string, never>; responses: { "200": Record<string, unknown> } }
  "GET /api/chats/{chat_id}": { body: never; parameters: { "path.chat_id": string }; responses: { "200": ApiSchemas["Chat"]; "422": ApiSchemas["HTTPValidationError"] } }
  "PATCH /api/chats/{chat_id}": { body: ApiSchemas["ChatUpdate"]; parameters: { "path.chat_id": string }; responses: { "200": ApiSchemas["Chat"]; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/chats/{chat_id}/archive": { body: ApiSchemas["ChatArchive"]; parameters: { "path.chat_id": string }; responses: { "200": ApiSchemas["Chat"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/chats/{chat_id}/messages": { body: never; parameters: { "path.chat_id": string; "query.limit"?: number }; responses: { "200": Array<ApiSchemas["Message"]>; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/chats/{chat_id}/messages": { body: ApiSchemas["MessageCreate"]; parameters: { "path.chat_id": string }; responses: { "201": ApiSchemas["Message"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/connections": { body: never; parameters: { "query.include_archived"?: boolean }; responses: { "200": Array<ApiSchemas["ProviderConnection"]>; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/connections": { body: ApiSchemas["ProviderConnectionCreate"]; parameters: Record<string, never>; responses: { "201": ApiSchemas["ProviderConnection"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/connections/{connection_id}": { body: never; parameters: { "path.connection_id": string }; responses: { "200": ApiSchemas["ProviderConnection"]; "422": ApiSchemas["HTTPValidationError"] } }
  "PATCH /api/connections/{connection_id}": { body: ApiSchemas["ProviderConnectionUpdate"]; parameters: { "path.connection_id": string }; responses: { "200": ApiSchemas["ProviderConnection"]; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/connections/{connection_id}/archive": { body: never; parameters: { "path.connection_id": string; "query.expected_version": number }; responses: { "200": ApiSchemas["ProviderConnection"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/connections/{connection_id}/models": { body: never; parameters: { "path.connection_id": string }; responses: { "200": Record<string, unknown>; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/connections/{connection_id}/test": { body: never; parameters: { "path.connection_id": string }; responses: { "200": ApiSchemas["ProviderTest"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/harness_profiles": { body: never; parameters: { "query.include_archived"?: boolean }; responses: { "200": Array<ApiSchemas["HarnessProfile"]>; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/harness_profiles": { body: ApiSchemas["HarnessProfileCreate"]; parameters: Record<string, never>; responses: { "201": ApiSchemas["HarnessProfile"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/harness_profiles/{harness_id}": { body: never; parameters: { "path.harness_id": string }; responses: { "200": ApiSchemas["HarnessProfile"]; "422": ApiSchemas["HTTPValidationError"] } }
  "PATCH /api/harness_profiles/{harness_id}": { body: ApiSchemas["HarnessProfileUpdate"]; parameters: { "path.harness_id": string }; responses: { "200": ApiSchemas["HarnessProfile"]; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/harness_profiles/{harness_id}/archive": { body: never; parameters: { "path.harness_id": string; "query.expected_version": number }; responses: { "200": ApiSchemas["HarnessProfile"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/health": { body: never; parameters: Record<string, never>; responses: { "200": Record<string, string> } }
  "GET /api/messages/{message_id}": { body: never; parameters: { "path.message_id": string }; responses: { "200": ApiSchemas["Message"]; "422": ApiSchemas["HTTPValidationError"] } }
  "PATCH /api/messages/{message_id}": { body: ApiSchemas["MessageUpdate"]; parameters: { "path.message_id": string }; responses: { "200": ApiSchemas["Message"]; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/messages/{message_id}/archive": { body: ApiSchemas["ChatArchive"]; parameters: { "path.message_id": string }; responses: { "200": ApiSchemas["Message"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/openapi.json": { body: never; parameters: Record<string, never>; responses: { "200": Record<string, unknown> } }
  "GET /api/projects": { body: never; parameters: { "query.include_archived"?: boolean }; responses: { "200": Array<ApiSchemas["Project"]>; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/projects": { body: ApiSchemas["ProjectCreate"]; parameters: Record<string, never>; responses: { "201": ApiSchemas["Project"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/projects/{project_id}": { body: never; parameters: { "path.project_id": string }; responses: { "200": ApiSchemas["Project"]; "422": ApiSchemas["HTTPValidationError"] } }
  "PATCH /api/projects/{project_id}": { body: ApiSchemas["ProjectUpdate"]; parameters: { "path.project_id": string }; responses: { "200": ApiSchemas["Project"]; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/projects/{project_id}/archive": { body: ApiSchemas["ProjectArchive"]; parameters: { "path.project_id": string }; responses: { "200": ApiSchemas["Project"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/projects/{project_id}/chats": { body: never; parameters: { "path.project_id": string; "query.include_archived"?: boolean }; responses: { "200": Array<ApiSchemas["Chat"]>; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/projects/{project_id}/chats": { body: ApiSchemas["ChatCreate"]; parameters: { "path.project_id": string }; responses: { "201": ApiSchemas["Chat"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/readiness": { body: never; parameters: Record<string, never>; responses: { "200": unknown } }
  "GET /api/runs": { body: never; parameters: { "query.project_id"?: (string | null) }; responses: { "200": Array<ApiSchemas["Run"]>; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/runs": { body: ApiSchemas["RunStart"]; parameters: Record<string, never>; responses: { "201": ApiSchemas["Run"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/runs/{run_id}": { body: never; parameters: { "path.run_id": string }; responses: { "200": ApiSchemas["Run"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/runs/{run_id}/commands": { body: never; parameters: { "path.run_id": string }; responses: { "200": Array<ApiSchemas["CommandAccepted"]>; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/runs/{run_id}/commands": { body: ApiSchemas["RunCommand"]; parameters: { "path.run_id": string }; responses: { "200": ApiSchemas["CommandAccepted"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/schema/events": { body: never; parameters: Record<string, never>; responses: { "200": Record<string, unknown> } }
  "GET /api/schema/nodes": { body: never; parameters: Record<string, never>; responses: { "200": Record<string, unknown> } }
  "GET /api/system/events": { body: never; parameters: Record<string, never>; responses: { "200": unknown } }
  "GET /api/system/status": { body: never; parameters: Record<string, never>; responses: { "200": Record<string, unknown> } }
  "GET /api/templates": { body: never; parameters: { "query.include_archived"?: boolean }; responses: { "200": Array<ApiSchemas["PipelineTemplate"]>; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/templates": { body: ApiSchemas["PipelineTemplateCreate"]; parameters: Record<string, never>; responses: { "201": ApiSchemas["PipelineTemplate"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/templates/{template_id}": { body: never; parameters: { "path.template_id": string }; responses: { "200": ApiSchemas["PipelineTemplate"]; "422": ApiSchemas["HTTPValidationError"] } }
  "PATCH /api/templates/{template_id}": { body: ApiSchemas["PipelineTemplateUpdate"]; parameters: { "path.template_id": string }; responses: { "200": ApiSchemas["PipelineTemplate"]; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/templates/{template_id}/archive": { body: never; parameters: { "path.template_id": string; "query.expected_version": number }; responses: { "200": ApiSchemas["PipelineTemplate"]; "422": ApiSchemas["HTTPValidationError"] } }
  "PUT /api/templates/{template_id}/draft": { body: ApiSchemas["PipelineDraftUpdate"]; parameters: { "path.template_id": string }; responses: { "200": ApiSchemas["PipelineTemplate"]; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/templates/{template_id}/publish": { body: ApiSchemas["DraftPublish"]; parameters: { "path.template_id": string }; responses: { "201": ApiSchemas["PipelineVersion"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/templates/{template_id}/versions": { body: never; parameters: { "path.template_id": string }; responses: { "200": Array<ApiSchemas["PipelineVersion"]>; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/templates/{template_id}/versions": { body: ApiSchemas["PipelineVersionCreate"]; parameters: { "path.template_id": string }; responses: { "201": ApiSchemas["PipelineVersion"]; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /api/versions/{version_id}": { body: never; parameters: { "path.version_id": string }; responses: { "200": ApiSchemas["PipelineVersion"]; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/versions/{version_id}/bindings": { body: ApiSchemas["PipelineBindingCreate"]; parameters: { "path.version_id": string }; responses: { "201": ApiSchemas["PipelineBinding"]; "422": ApiSchemas["HTTPValidationError"] } }
  "POST /api/workspace/probe": { body: Record<string, string>; parameters: Record<string, never>; responses: { "200": Record<string, unknown>; "422": ApiSchemas["HTTPValidationError"] } }
  "GET /{path}": { body: never; parameters: { "path.path": string }; responses: { "200": unknown; "422": ApiSchemas["HTTPValidationError"] } }
}

export interface NodeSchemas {
  "AgentTask": { "config": { "prompt": string; "role": string; [key: string]: unknown }; "id": string; "type": "AgentTask"; [key: string]: unknown }
  "CollectContext": { "config": { "context_paths"?: Array<unknown>; "mode"?: "collect" | "resolve_requests"; "sources"?: Array<unknown>; [key: string]: unknown }; "id": string; "type": "CollectContext"; [key: string]: unknown }
  "Command": { "config": { "commands": Array<{ "args": Array<string>; "cwd"?: string; "env"?: Record<string, unknown>; "id"?: string; "max_output_bytes"?: number; "program": string; "required"?: boolean; "retry_safety"?: "safe" | "unsafe"; "success_exit_codes"?: Array<number>; "timeout_seconds"?: number; [key: string]: unknown }>; "failure_policy"?: "collect_all" | "stop_on_failure"; [key: string]: unknown }; "id": string; "type": "Command"; [key: string]: unknown }
  "Condition": { "expression": Record<string, unknown>; "id": string; "type": "Condition"; [key: string]: unknown }
  "End": { "id": string; "type": "End" }
  "GitCommit": { "id": string; "type": "GitCommit"; [key: string]: unknown }
  "LLMRequest": { "config": { "connection_id": string; "model": string; "prompt": string; [key: string]: unknown }; "id": string; "type": "LLMRequest"; [key: string]: unknown }
  "PlanControl": { "id": string; "operation": "select_next" | "record_verified" | "record_final_check" | "attach_commit"; "type": "PlanControl"; [key: string]: unknown }
  "Start": { "id": string; "type": "Start" }
}
