"""Export server OpenAPI/node schemas and deterministic TypeScript contracts.

Run from backend: uv run python ../scripts/generate_contracts.py [--check].
No service, database, installed harness or network is needed.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from agents_ide.api.app import create_app
from agents_ide.api.domain import node_schemas

ROOT = Path(__file__).resolve().parents[1]


def ts_type(schema: dict[str, Any] | bool) -> str:
    if schema is True:
        return "unknown"
    if schema is False:
        return "never"
    if "$ref" in schema:
        return f"ApiSchemas[{json.dumps(schema['$ref'].rsplit('/', 1)[1])}]"
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(item, ensure_ascii=False) for item in schema["enum"])
    for key, separator in (("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")):
        if key in schema:
            return "(" + separator.join(ts_type(item) for item in schema[key]) + ")"
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if kind == "object" or "properties" in schema:
        required = schema.get("required", [])
        properties = schema.get("properties", {})
        fields = [
            f"{json.dumps(name)}{'' if name in required else '?'}: {ts_type(value)}"
            for name, value in sorted(properties.items())
        ]
        additional = schema.get("additionalProperties", True)
        if not fields:
            return f"Record<string, {ts_type(additional)}>"
        if additional:
            fields.append(f"[key: string]: {ts_type(additional)}")
        return "{ " + "; ".join(fields) + " }"
    if kind in ("string", "boolean", "null"):
        return str(kind)
    if kind in ("integer", "number"):
        return "number"
    if not schema or kind is None:
        return "unknown"
    raise ValueError(f"Unsupported schema type: {kind}")


def generated_files() -> dict[Path, str]:
    api = create_app().openapi()
    nodes = node_schemas()
    lines = [
        "// Generated by scripts/generate_contracts.py. Do not edit.",
        "export interface ApiSchemas {",
    ]
    for name, schema in sorted(api["components"]["schemas"].items()):
        lines.append(f"  {json.dumps(name)}: {ts_type(schema)}")
    lines.append("}\n\nexport interface ApiOperations {")
    for path, methods in sorted(api["paths"].items()):
        for method, operation in sorted(methods.items()):
            request = (
                operation.get("requestBody", {}).get("content", {}).get("application/json", {})
            )
            responses = operation["responses"]
            response_fields = []
            for code, response in sorted(responses.items()):
                schema = response.get("content", {}).get("application/json", {}).get("schema", {})
                response_fields.append(f"{json.dumps(code)}: {ts_type(schema)}")
            parameters = operation.get("parameters", [])
            params = "; ".join(
                f"{json.dumps(item['in'] + '.' + item['name'])}"
                f"{'' if item.get('required') else '?'}: {ts_type(item['schema'])}"
                for item in parameters
            )
            parameter_type = f"{{ {params} }}" if params else "Record<string, never>"
            lines.append(
                f"  {json.dumps(method.upper() + ' ' + path)}: {{ "
                f"body: {ts_type(request.get('schema', False))}; "
                f"parameters: {parameter_type}; responses: {{ {'; '.join(response_fields)} }} }}"
            )
    lines.append("}\n\nexport interface NodeSchemas {")
    for name, schema in sorted(nodes["nodes"].items()):
        lines.append(f"  {json.dumps(name)}: {ts_type(schema)}")
    lines.append("}\n")
    return {
        ROOT / "frontend/src/api/generated.ts": "\n".join(lines),
        ROOT / "docs/api/openapi.json": json.dumps(
            api, indent=2, ensure_ascii=False, sort_keys=True
        )
        + "\n",
        ROOT / "docs/api/nodes.json": json.dumps(
            nodes, indent=2, ensure_ascii=False, sort_keys=True
        )
        + "\n",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in generated_files().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print("Regenerate server contracts: " + ", ".join(stale))
        return 1
    print("Server contracts are synchronized" if args.check else "Server contracts generated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
